import { container } from 'tsyringe';
import { IPackageTypeService } from './services/interfaces/packagetype.service.interface';
import { PackageTypeService } from './services/packagetype.service';
import { IPackageTypeRepository } from './repositories/interfaces/packagetype.repository.interface';
import { PackageTypeRepository } from './repositories/packagetype.repository';
import { IPackageCategoryService } from './services/interfaces/packagecategory.service.interface';
import { PackageCategoryService } from './services/packagecategory.service';
import { IPackageCategoryRepository } from './repositories/interfaces/packagecategory.repository.interface';
import { PackageCategoryRepository } from './repositories/packagecategory.repository';
import { IPackageCategoryMappingService } from './services/interfaces/packagecategorymapping.service.interface';
import { PackageCategoryMappingService } from './services/packagecategorymapping.service';
import { IPackageCategoryMappingRepository } from './repositories/interfaces/packagecategorymapping.repository.interface';
import { PackageCategoryMappingRepository } from './repositories/packagecategorymapping.repository';
import { IPackageActivityService } from './services/interfaces/packageactivity.service.interface';
import { PackageActivityService } from './services/packageactivity.service';
import { IPackageActivityRepository } from './repositories/interfaces/packageactivity.repository.interface';
import { PackageActivityRepository } from './repositories/packageactivity.repository';
import { IPackageActivityMappingService } from './services/interfaces/packageactivitymapping.service.interface';
import { PackageActivityMappingService } from './services/packageactivitymapping.service';
import { IPackageActivityMappingRepository } from './repositories/interfaces/packageactivitymapping.repository.interface';
import { PackageActivityMappingRepository } from './repositories/packageactivitymapping.repository';
import { IPackageSnapshotService } from './services/interfaces/packagesnapshot.service.interface';
import { PackageSnapshotService } from './services/packagesnapshot.service';
import { IPackageSnapshotRepository } from './repositories/interfaces/packagesnapshot.repository.interface';
import { PackageSnapshotRepository } from './repositories/packagesnapshot.repository';
import { IPackageSnapshotMappingService } from './services/interfaces/packagesnapshotmapping.service.interface';
import { PackageSnapshotMappingService } from './services/packagesnapshotmapping.service';
import { IPackageSnapshotMappingRepository } from './repositories/interfaces/packagesnapshotmapping.repository.interface';
import { PackageSnapshotMappingRepository } from './repositories/packagesnapshotmapping.repository';
import { IPackageService } from './services/interfaces/package.service.interface';
import { PackageService } from './services/package.service';
import { IPackageRepository } from './repositories/interfaces/package.repository.interface';
import { PackageRepository } from './repositories/package.repository';
import { IPackageCityService } from './services/interfaces/packagecity.service.interface';
import { PackageCityService } from './services/packagecity.service';
import { IPackageCityRepository } from './repositories/interfaces/packagecity.repository.interface';
import { PackageCityRepository } from './repositories/packagecity.repository';
import { IPackageCityDayService } from './services/interfaces/packagecityday.service.interface';
import { PackageCityDayService } from './services/packagecityday.service';
import { IPackageCityDayRepository } from './repositories/interfaces/packagecityday.repository.interface';
import { PackageCityDayRepository } from './repositories/packagecityday.repository';
import { IPackageCityDayTravelService } from './services/interfaces/packagecitydaytravel.service.interface';
import { PackageCityDayTravelService } from './services/packagecitydaytravel.service';
import { IPackageCityDayTravelRepository } from './repositories/interfaces/packagecitydaytravel.repository.interface';
import { PackageCityDayTravelRepository } from './repositories/packagecitydaytravel.repository';
import { IPackageCityDaySightseeingService } from './services/interfaces/packagecitydaysightseeing.service.interface';
import { PackageCityDaySightseeingService } from './services/packagecitydaysightseeing.service';
import { IPackageCityDaySightseeingRepository } from './repositories/interfaces/packagecitydaysightseeing.repository.interface';
import { PackageCityDaySightseeingRepository } from './repositories/packagecitydaysightseeing.repository';
import { IPackageCityDayHotelService } from './services/interfaces/packagecitydayhotel.service.interface';
import { PackageCityDayHotelService } from './services/packagecitydayhotel.service';
import { IPackageCityDayHotelRepository } from './repositories/interfaces/packagecitydayhotel.repository.interface';
import { PackageCityDayHotelRepository } from './repositories/packagecitydayhotel.repository';
import { IPackageCityDayMealService } from './services/interfaces/packagecitydaymeal.service.interface';
import { PackageCityDayMealService } from './services/packagecitydaymeal.service';
import { IPackageCityDayMealRepository } from './repositories/interfaces/packagecitydaymeal.repository.interface';
import { PackageCityDayMealRepository } from './repositories/packagecitydaymeal.repository';
import { IPackageCompleteService } from './services/interfaces/package-complete.service.interface';
import { PackageCompleteService } from './services/package-complete.service';

export const registerDependencies = () => {
  container.register<IPackageTypeService>('IPackageTypeService', { useClass: PackageTypeService });
  container.register<IPackageTypeRepository>('IPackageTypeRepository', { useClass: PackageTypeRepository });
  container.register<IPackageCategoryService>('IPackageCategoryService', { useClass: PackageCategoryService });
  container.register<IPackageCategoryRepository>('IPackageCategoryRepository', { useClass: PackageCategoryRepository });
  container.register<IPackageCategoryMappingService>('IPackageCategoryMappingService', { useClass: PackageCategoryMappingService });
  container.register<IPackageCategoryMappingRepository>('IPackageCategoryMappingRepository', { useClass: PackageCategoryMappingRepository });
  container.register<IPackageActivityService>('IPackageActivityService', { useClass: PackageActivityService });
  container.register<IPackageActivityRepository>('IPackageActivityRepository', { useClass: PackageActivityRepository });
  container.register<IPackageActivityMappingService>('IPackageActivityMappingService', { useClass: PackageActivityMappingService });
  container.register<IPackageActivityMappingRepository>('IPackageActivityMappingRepository', { useClass: PackageActivityMappingRepository });
  container.register<IPackageSnapshotService>('IPackageSnapshotService', { useClass: PackageSnapshotService });
  container.register<IPackageSnapshotRepository>('IPackageSnapshotRepository', { useClass: PackageSnapshotRepository });
  container.register<IPackageSnapshotMappingService>('IPackageSnapshotMappingService', { useClass: PackageSnapshotMappingService });
  container.register<IPackageSnapshotMappingRepository>('IPackageSnapshotMappingRepository', { useClass: PackageSnapshotMappingRepository });
  container.register<IPackageService>('IPackageService', { useClass: PackageService });
  container.register<IPackageRepository>('IPackageRepository', { useClass: PackageRepository });
  container.register<IPackageCityService>('IPackageCityService', { useClass: PackageCityService });
  container.register<IPackageCityRepository>('IPackageCityRepository', { useClass: PackageCityRepository });
  container.register<IPackageCityDayService>('IPackageCityDayService', { useClass: PackageCityDayService });
  container.register<IPackageCityDayRepository>('IPackageCityDayRepository', { useClass: PackageCityDayRepository });
  container.register<IPackageCityDayTravelService>('IPackageCityDayTravelService', { useClass: PackageCityDayTravelService });
  container.register<IPackageCityDayTravelRepository>('IPackageCityDayTravelRepository', { useClass: PackageCityDayTravelRepository });
  container.register<IPackageCityDaySightseeingService>('IPackageCityDaySightseeingService', { useClass: PackageCityDaySightseeingService });
  container.register<IPackageCityDaySightseeingRepository>('IPackageCityDaySightseeingRepository', { useClass: PackageCityDaySightseeingRepository });
  container.register<IPackageCityDayHotelService>('IPackageCityDayHotelService', { useClass: PackageCityDayHotelService });
  container.register<IPackageCityDayHotelRepository>('IPackageCityDayHotelRepository', { useClass: PackageCityDayHotelRepository });
  container.register<IPackageCityDayMealService>('IPackageCityDayMealService', { useClass: PackageCityDayMealService });
  container.register<IPackageCityDayMealRepository>('IPackageCityDayMealRepository', { useClass: PackageCityDayMealRepository });
  container.register<IPackageCompleteService>('IPackageCompleteService', { useClass: PackageCompleteService });
  console.log('All module dependencies registered');
};

export const clearDependencies = () => {
  container.reset();
};
